name: deploy api staging

on:
  workflow_run:
    workflows: ["build api"]
    types:
      - completed

  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: login to heroku container registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login -u ${{ secrets.HEROKU_LOGIN }} --password-stdin registry.heroku.com

      - name: create a new tag for latest image
        run: docker tag maximeoger/jdp-api registry.heroku.com/jdp-api/web

      - name: push to container registry
        run: docker push registry.heroku.com/jdp-api/web