name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      working-directory: ./packages/server
      - uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: lint.ci

      working-directory: ./packages/common
      - uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: lint.ci
      
      working-directory: ./packages/front
      - uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: lint.ci

